//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommunityMember()
        {
            this.CommunityPosts = new HashSet<CommunityPost>();
        }
    
        public System.Guid CommunityMembersID { get; set; }
        public System.Guid CommunityID { get; set; }
        public string Login { get; set; }
        public int RoleID { get; set; }
    
        public virtual Access_for_Comunity Access_for_Comunity { get; set; }
        public virtual Community Community { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunityPost> CommunityPosts { get; set; }
    }
}
