//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommunityPost()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid CommunityPostID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.Guid CommunityMembersID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual CommunityMember CommunityMember { get; set; }
    }
}
