//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtectedUser
    {
        public string Login { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Patronymic { get; set; }
    }
}
