//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPost
    {
        public System.Guid UserPostID { get; set; }
        public string Login { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    
        public virtual User User { get; set; }
    }
}
